services:
  front:
    build:
      context: ./frontCripta
      target: dev
    container_name: criptaDoge-front
    restart: always
    volumes:
      - ./frontCripta:/app
      - front_node_modules:/app/node_modules
    expose:
      - "5173"
    env_file:
      - ./.env.development
    command: sh -c "npm install && npm run dev"

  back:
    build:
      context: ./backCripta
      target: dev
    container_name: criptaDoge-back
    restart: always
    volumes:
      - ./backCripta:/app
    environment:
      MONGO_URL: mongodb://mongo:27017/cripta-db
      FRONTEND_URL: "http://localhost:8080"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
    expose:
      - "3000"
    env_file:
      - ./.env.development
    command: sh -c "yarn install --immutable && npx prisma generate && npx prisma db push --force-reset --accept-data-loss && yarn seed && yarn start:dev"

  db:
    image: postgres:17-alpine
    container_name: criptaDoge-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 180s
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo:
    image: mongo:8
    container_name: criptaDoge-mongo
    restart: always
    command: sh -c "rm -rf /data/db/* && docker-entrypoint.sh mongod"
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: criptaDoge-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - back

volumes:
  front_node_modules:
  db_data:
  mongo_data:
